export const ADMIN_SECRET = "admin-92Kf8s";

export const VIEWER_PERMISSIONS = {
  LOG_MATCH: "LOG_MATCH",
  EDIT_MATCH: "EDIT_MATCH",
  DELETE_MATCH: "DELETE_MATCH",
  ADD_SESSION: "ADD_SESSION",
  EDIT_SESSION: "EDIT_SESSION",
  DELETE_SESSION: "DELETE_SESSION",
  EDIT_STOCK: "EDIT_STOCK",
  DELETE_STOCK: "DELETE_STOCK",
  EDIT_PAYMENT: "EDIT_PAYMENT",
  DELETE_PAYMENT: "DELETE_PAYMENT",
} as const;

export type ViewerPermission = typeof VIEWER_PERMISSIONS[keyof typeof VIEWER_PERMISSIONS];

export const DEFAULT_VIEWER_PERMISSIONS: ViewerPermission[] = [
  VIEWER_PERMISSIONS.LOG_MATCH,
  VIEWER_PERMISSIONS.EDIT_MATCH,
  VIEWER_PERMISSIONS.DELETE_MATCH,
];

export const ALL_VIEWER_PERMISSION_KEYS: ViewerPermission[] = Object.values(VIEWER_PERMISSIONS);

export const VIEWER_SESSION_COOKIE = "cockcount_viewer_unlock";
export const VIEWER_UNLOCK_TTL_SECONDS = 3600; // 60 minutes
